### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by Madxmike** [primetoxinz/Modpacks#2]
Fancy fluid storage - https://minecraft.curseforge.com/projects/ffs-fancy-fluid-storage
Bagginses - https://minecraft.curseforge.com/projects/bagginses
Better Builders Wands - https://minecraft.curseforge.com/projects/better-builders-wands

**Comment by primetoxinz** [comment]
Gendustry
Cooking with Blockheads
Custom Arsmagica build
